# Generated by Django 4.1.7 on 2023-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModInscripción',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('NumeroTelefono', models.IntegerField()),
                ('FechaSeminario', models.DateField()),
                ('Empresa_Institucion', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Profesion', models.CharField(max_length=100)),
                ('Observaciones', models.TextField(max_length=1000)),
            ],
        ),
    ]
