# Generated by Django 4.1.7 on 2023-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django2App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modinscripción',
            name='Observaciones',
            field=models.TextField(),
        ),
    ]
